
hCraft_sources = Split("""
		main.cpp
		logger.cpp
		server.cpp
		player.cpp
		playerlist.cpp 
		packet.cpp
		scheduler.cpp
		entity.cpp
		position.cpp
		chunk.cpp
		world.cpp
		blocks.cpp
		worldgenerator.cpp
		flatgrass.cpp
		stringutils.cpp
		wordwrap.cpp
		threadpool.cpp
		worldprovider.cpp
		hwprovider.cpp
		utils.cpp
		rank.cpp
		permissions.cpp
		messages.cpp
		nbt.cpp
		window.cpp
		items.cpp
		slot.cpp
		sql.cpp
		lighting.cpp
		
		commands/command.cpp
		commands/help.cpp
		commands/me.cpp
		commands/ping.cpp
		commands/wcreate.cpp
		commands/wload.cpp
		commands/world.cpp
		commands/tp.cpp
		commands/nick.cpp
		commands/wunload.cpp
		commands/physics.cpp
		
		physics/sand.cpp
		""")

hCraft_libs = Split("""
		pthread
		event
		m
		yaml-cpp
		z
		sqlite3
		""")

Import('env')
env.Program(target = 'hCraft', source = hCraft_sources, LIBS = hCraft_libs)

