
hCraft_sources = Split("""
		main.cpp
		logger.cpp
		server.cpp
		player.cpp
		playerlist.cpp 
		packet.cpp
		scheduler.cpp
		entity.cpp
		position.cpp
		chunk.cpp
		world.cpp
		blocks.cpp
		stringutils.cpp
		wordwrap.cpp
		threadpool.cpp
		worldprovider.cpp
		hwprovider.cpp
		utils.cpp
		rank.cpp
		permissions.cpp
		messages.cpp
		nbt.cpp
		window.cpp
		items.cpp
		slot.cpp
		sql.cpp
		lighting.cpp
		manual.cpp
		world_transaction.cpp
		player_transaction.cpp
		block_physics.cpp
		pickup.cpp
		crafting.cpp
		editstage.cpp
		
		generation/worldgenerator.cpp
		generation/flatgrass.cpp
		generation/plains.cpp
		
		commands/command.cpp
		commands/help.cpp
		commands/me.cpp
		commands/ping.cpp
		commands/wcreate.cpp
		commands/wload.cpp
		commands/world.cpp
		commands/tp.cpp
		commands/nick.cpp
		commands/wunload.cpp
		commands/physics.cpp
		commands/select.cpp
		commands/fill.cpp
		commands/gm.cpp
		commands/line.cpp
		commands/bezier.cpp
		
		selection/cuboid_selection.cpp
		selection/block_selection.cpp
		selection/sphere_selection.cpp
		
		physics/sand.cpp
		physics/langtons_ant.cpp
		physics/water.cpp
		""")

hCraft_libs = Split("""
		pthread
		event
		event_pthreads
		m
		config++
		z
		sqlite3
		noise
		tbb
		""")

Import('env')
env.Program(target = 'hCraft', source = hCraft_sources, LIBS = hCraft_libs)

